plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.7.20'
}

apply plugin: 'kotlin-kapt'
apply plugin: 'dagger.hilt.android.plugin'


android {
    namespace 'com.demo.songexplorer'
    compileSdk 32

    defaultConfig {
        applicationId "com.demo.songexplorer"
        minSdk 21
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation project(path: ":features:song-discovery")
    implementation libs.android.dagger.hilt
    kapt libs.android.dagger.compiler
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.google.material
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.core.ktx
}